---
version: '3.4'
services:
  test:
    build:
      context: "."
      dockerfile: Dockerfile.ci
    volumes:
    - test_data:/usr/local/bundle
    - "./node_modules:/app/node_modules"
    environment:
      RACK_ENV: test
volumes:
  test_data: 
